// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyXKx3C9m9r3zk8wKYJgaRbhzTPHLYPKY',
    appId: '1:685007533336:web:2544ee85948ce84f2d5a6d',
    messagingSenderId: '685007533336',
    projectId: 'peace-mind-ai',
    authDomain: 'peace-mind-ai.firebaseapp.com',
    storageBucket: 'peace-mind-ai.firebasestorage.app',
    measurementId: 'G-FKLY19DW88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWyQz9s1zYEWEI9dPtskHCEISaL7UF5E',
    appId: '1:685007533336:android:883c42df42e64cd92d5a6d',
    messagingSenderId: '685007533336',
    projectId: 'peace-mind-ai',
    storageBucket: 'peace-mind-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDfDpXrFALSy6uoIXHXXlLGXpBWo89sY',
    appId: '1:685007533336:ios:69e498bbe80855752d5a6d',
    messagingSenderId: '685007533336',
    projectId: 'peace-mind-ai',
    storageBucket: 'peace-mind-ai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyXKx3C9m9r3zk8wKYJgaRbhzTPHLYPKY',
    appId: '1:685007533336:web:bd41054d84c2015e2d5a6d',
    messagingSenderId: '685007533336',
    projectId: 'peace-mind-ai',
    authDomain: 'peace-mind-ai.firebaseapp.com',
    storageBucket: 'peace-mind-ai.firebasestorage.app',
    measurementId: 'G-N46JG4E4LB',
  );
}
